# Site
title:              김지광
bio:                '소프트웨어 개발을 하면서 공부한 것을 정리하고 공유하는 페이지입니다.'
description:        "소프트웨어 개발을 하면서 공부한 것을 정리하고 공유하는 페이지입니다."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/profile.jpg'
background:         'assets/img/background.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             ko_KR
url:                https://kimjg.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   kimjg

# Social
# if you don't have any of social below, comment the line.
google:
  analytics:
    tracking_id: 'G-85N2L3XD6J'
github-url:         kimjg

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
